server:
  port: ${SERVER_PORT:8080}
  max-http-header-size: 10000000

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  application:
    name: ms-sample
  jackson:
    default-property-inclusion: non_null


management.endpoints.web.exposure.include: '*'

security:
  enabled: false

spring.banner:
  charset: UTF-8
  location: classpath:banner.txt

openai:
  api-key: ${OPENAI_API_KEY}

logging:
  level:
    org:
      apache:
        http: DEBUG